name: Matrix CI Build (Node.js & Python)

on: [push, pull_request]

jobs:
  test-node:
    name: Node.js CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Install dependencies
        run: |
         npm Install
        
      - name: Run Node.js test
        run: |
         echo "Testing Node.js Version ${{ matrix.node-version }}"
         echo "1 + 2 = $((1 + 2))"
  
  test-python:
    name: Python CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-pythone@v5
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Install dependencies
        run: |
         python -m pip Install --upgrade pip
         pip install pytest
        
      - name: Run python test
        run: |
         echo "Testing python Version ${{ matrix.python-version }}"
         echo " assert 1 + 2 == 3" | python
